addons:
  apt:
    packages:
      - libxml2-utils

env:
  global:
    - secure: "J7Z7mMQuoiX+4+6FDXH1mH6MnMBSvz8VsX92rXnl9+Q63QnW85CBYmiAD/GfVNUxdxQGo6h/w0eYGg6Uzj5Dz613E46GSgsoICFQTzUpW3YJi9FxxXPU0f//RJAmrqJ3jjTLNRu+0OHpDktjJw99btOMQmTpiaFuk8IfWgX1wRI="
    - secure: "ZJ8Yi7nWIOeJhm/Hd+vzCbFrGaLTHFoKzlna0+hdsN3vOlygi5Kf3RdUpcgVqK+dk3DbWvb6d0N2KxdkwbkdPMz2IEt7GXCkAcDxK/zpaEzLZmqNmumS20l/avZDLWgRLYei7BM08Hvw6pXiQNLVC+xAfBPA5phjvFqb3IjXRTw="

language: java
jdk:
    - openjdk7
    - oraclejdk8

after_success:
  - export VERSION=$(echo "cat //*[local-name()='project']/*[local-name()='version']/text()" | xmllint --nocdata --shell pom.xml | sed '1d;$d')
  - 'if [ "$TRAVIS_BRANCH" = "master" ] && [ "$TRAVIS_PULL_REQUEST" = "false" ] && [[ "$VERSION" =~ \-SNAPSHOT$ ]]; then mvn deploy --settings travis-settings.xml -DskipTests=true -B; fi'