addons:
  apt:
    packages:
      - libxml2-utils

env:
  global:
    - secure: "r8cB+fja8mlYsacCZP0HZMFL6JvZk9vpxZ4Y/sBkEyUQTP6U5ve8+UNeoP90OChbJt6bgZqI5RSbc0Ib9PEB7HZs6mz9JZXWq9ay4s//uZjkrIHH85jHq7tfZRz7eEkoi3PGfyVWOtWDCb9NQFmJLIknC2/b+u/hZRv3YxhzLKE="
    - secure: "XUPa+8qGdZY3VTHCa7F6NgTOlFuXM4CLUWf3lfXSsANuLicAtwiKOwxPE0I6kt7O5iqjeWnOje0vcMuqEK96LfSxj3V9on1SRY/4B6ltSG8AnxZipvoxZ/7rZZ+8MEufzihvMv9v1QliqgSBMeT3Yb9mxfmEcD2ZnvuMbCCkFsA="

language: java
jdk:
    - openjdk7
    - oraclejdk8

after_success:
  - export VERSION=$(echo "cat //*[local-name()='project']/*[local-name()='version']/text()" | xmllint --nocdata --shell pom.xml | sed '1d;$d')
  - 'if [ "$TRAVIS_BRANCH" = "master" ] && [ "$TRAVIS_PULL_REQUEST" = "false" ] && [[ "$VERSION" =~ \-SNAPSHOT$ ]]; then mvn deploy --settings travis-settings.xml -DskipTests=true -B; fi'