addons:
  apt:
    packages:
      - libxml2-utils

language: java
jdk:
    - openjdk7
    - oraclejdk8

after_success:
  - export VERSION=$(echo "cat //*[local-name()='project']/*[local-name()='version']/text()" | xmllint --nocdata --shell pom.xml | sed '1d;$d')
  - echo $VERSION
  - 'if [[ "$VERSION" =~ \-SNAPSHOT$ ]]; then echo SNAPSHOT; fi'